name: API

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python in a virtual env
      run: |
        if [[ `uname` != "Darwin" ]]; then sudo apt -y install python3-venv; fi
        python3 -m venv .env
    - name: Install dependencies
      run: |
        source .env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: run code
        run: |
          export FLASK_APP=main.py
          export FLASK_ENV=development
          flask run --host=0.0.0.0 --port=5000 &
